{
  "id": "BIT-mlflow-2024-27133",
  "details": "Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset. This issue leads to a client-side RCE when running the recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over dataset table fields.",
  "aliases": [
    "CVE-2024-27133",
    "GHSA-3v79-q7ph-j75h"
  ],
  "modified": "2024-07-18T07:56:34.499Z",
  "published": "2024-03-31T18:21:40.530Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:lfprojects:mlflow:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:lfprojects:mlflow:*:*:*:*:*:python:*:*"
    ],
    "severity": "High"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/mlflow/mlflow/pull/10893"
    },
    {
      "type": "WEB",
      "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "mlflow",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/mlflow"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.10.0"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/mlflow/BIT-mlflow-2024-27133.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}