{
  "id": "BIT-python-2023-33595",
  "details": "CPython v3.12.0 alpha 7 was discovered to contain a heap use-after-free via the function ascii_decode at /Objects/unicodeobject.c.",
  "aliases": [
    "BIT-python-min-2023-33595",
    "CVE-2023-33595",
    "PSF-2023-3"
  ],
  "modified": "2025-01-16T09:11:58.202055Z",
  "published": "2024-03-06T11:03:43.189Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:python:python:3.12.0:alpha7:*:*:*:*:*:*",
      "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
    ],
    "severity": "Medium"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/issues/103824"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/103993/commits/c120bc2d354ca3d27d0c7a53bf65574ddaabaf3a"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "python",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.12.0-alpha0"
            },
            {
              "fixed": "3.12.0-alpha8"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/python/BIT-python-2023-33595.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}