{
  "id": "BIT-gitlab-2021-22229",
  "details": "An issue has been discovered in GitLab CE/EE affecting all versions starting with 12.8. Under a special condition it was possible to access data of an internal repository through project fork done by a project member.",
  "aliases": [
    "CVE-2021-22229"
  ],
  "modified": "2025-02-26T07:48:40.248Z",
  "published": "2024-03-06T11:19:35.497Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
    ],
    "severity": "High"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22229.json"
    },
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/332609"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "gitlab",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/gitlab"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "12.8.0"
            },
            {
              "fixed": "13.11.6"
            },
            {
              "introduced": "13.12.0"
            },
            {
              "fixed": "13.12.6"
            },
            {
              "introduced": "14.0.0"
            },
            {
              "fixed": "14.0.2"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2021-22229.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}