{
  "id": "GO-2021-0079",
  "summary": "Panic in github.com/bytom/bytom",
  "details": "A malformed query can cause an out-of-bounds panic due to improper validation of arguments. If processing queries from untrusted parties, this may be used as a vector for denial of service attacks.",
  "aliases": [
    "CVE-2018-18206",
    "GHSA-vc3x-gx6c-g99f"
  ],
  "modified": "2024-05-20T16:03:47Z",
  "published": "2021-04-14T20:04:52Z",
  "database_specific": {
    "review_status": "REVIEWED",
    "url": "https://pkg.go.dev/vuln/GO-2021-0079"
  },
  "references": [
    {
      "type": "FIX",
      "url": "https://github.com/Bytom/bytom/pull/1307"
    },
    {
      "type": "FIX",
      "url": "https://github.com/Bytom/bytom/commit/1ac3c8ac4f2b1e1df9675228290bda6b9586ba42"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "github.com/bytom/bytom",
        "ecosystem": "Go",
        "purl": "pkg:golang/github.com/bytom/bytom"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.0.4-0.20180831054840-1ac3c8ac4f2b"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "imports": [
          {
            "path": "github.com/bytom/bytom/p2p/discover",
            "symbols": [
              "Network.checkTopicRegister"
            ]
          }
        ]
      },
      "database_specific": {
        "source": "https://vuln.go.dev/ID/GO-2021-0079.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "@yahtoo"
    }
  ]
}